version: '3'
services:
  web:
    image: webapp-flask
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    volumes:
      - "./flask_app:/code"
    ports:
      - "5000:5000"
  redis:
    image: redis
    volumes:
      - "./redis-data/:/data"
