version: '3'
services:
  web:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/code"
    ports:
      - "5000:5000"
  redis:
    image: redis
